import React from 'react';
import {
  Droplet,
  Dumbbell,
  BookOpen,
  Sparkles,
  Leaf,
  Moon,
  Sun,
  Heart,
  Flame,
  Bike,
  Footprints,
  Apple,
  Coffee,
  Brain,
  Music,
  Code,
  Palette,
  Smile,
  Target,
  Bed,
  Clock,
  Pill,
  Utensils,
  Wallet,
  LucideIcon,
} from 'lucide-react';
import { HabitIconKey } from '../types';

export type IconCategoryFilter = 'All' | 'Health' | 'Fitness' | 'Mindfulness' | 'Lifestyle';

export interface HabitIconDefinition {
  id: HabitIconKey;
  label: string;
  category: IconCategoryFilter;
  Icon: LucideIcon;
  bgColor: string;
  activeBg: string;
  textColor: string;
  ringColor: string;
  emoji: string;
  description: string;
}

export const HABIT_ICONS_LIST: HabitIconDefinition[] = [
  // Health & Body
  {
    id: 'water',
    label: 'Hydration',
    category: 'Health',
    Icon: Droplet,
    bgColor: 'bg-sky-50',
    activeBg: 'bg-sky-500',
    textColor: 'text-sky-600',
    ringColor: 'ring-sky-500',
    emoji: '💧',
    description: 'Drink water & stay hydrated',
  },
  {
    id: 'heart',
    label: 'Cardio / Heart',
    category: 'Health',
    Icon: Heart,
    bgColor: 'bg-rose-50',
    activeBg: 'bg-rose-500',
    textColor: 'text-rose-600',
    ringColor: 'ring-rose-500',
    emoji: '❤️',
    description: 'Cardiovascular health & vitals',
  },
  {
    id: 'apple',
    label: 'Healthy Eating',
    category: 'Health',
    Icon: Apple,
    bgColor: 'bg-emerald-50',
    activeBg: 'bg-emerald-600',
    textColor: 'text-emerald-600',
    ringColor: 'ring-emerald-600',
    emoji: '🍎',
    description: 'Clean nutrition & fruits',
  },
  {
    id: 'pill',
    label: 'Supplements',
    category: 'Health',
    Icon: Pill,
    bgColor: 'bg-teal-50',
    activeBg: 'bg-teal-600',
    textColor: 'text-teal-600',
    ringColor: 'ring-teal-600',
    emoji: '💊',
    description: 'Daily vitamins or medication',
  },
  {
    id: 'junk_food',
    label: 'Diet Discipline',
    category: 'Health',
    Icon: Utensils,
    bgColor: 'bg-orange-50',
    activeBg: 'bg-orange-500',
    textColor: 'text-orange-600',
    ringColor: 'ring-orange-500',
    emoji: '🥗',
    description: 'Mindful meals & avoid junk food',
  },

  // Fitness & Activity
  {
    id: 'exercise',
    label: 'Workout / Gym',
    category: 'Fitness',
    Icon: Dumbbell,
    bgColor: 'bg-purple-50',
    activeBg: 'bg-purple-600',
    textColor: 'text-purple-600',
    ringColor: 'ring-purple-600',
    emoji: '🏋️',
    description: 'Strength training & weights',
  },
  {
    id: 'flame',
    label: 'Calorie Burn',
    category: 'Fitness',
    Icon: Flame,
    bgColor: 'bg-amber-50',
    activeBg: 'bg-amber-500',
    textColor: 'text-amber-600',
    ringColor: 'ring-amber-500',
    emoji: '🔥',
    description: 'High intensity interval training',
  },
  {
    id: 'footprints',
    label: '10,000 Steps',
    category: 'Fitness',
    Icon: Footprints,
    bgColor: 'bg-lime-50',
    activeBg: 'bg-lime-600',
    textColor: 'text-lime-700',
    ringColor: 'ring-lime-600',
    emoji: '👟',
    description: 'Daily walking & active movement',
  },
  {
    id: 'bike',
    label: 'Cycling',
    category: 'Fitness',
    Icon: Bike,
    bgColor: 'bg-cyan-50',
    activeBg: 'bg-cyan-600',
    textColor: 'text-cyan-600',
    ringColor: 'ring-cyan-600',
    emoji: '🚴',
    description: 'Outdoor rides & spin classes',
  },
  {
    id: 'target',
    label: 'Goal Target',
    category: 'Fitness',
    Icon: Target,
    bgColor: 'bg-red-50',
    activeBg: 'bg-red-500',
    textColor: 'text-red-600',
    ringColor: 'ring-red-500',
    emoji: '🎯',
    description: 'Hitting daily metric targets',
  },

  // Mindfulness & Learning
  {
    id: 'meditate',
    label: 'Meditation',
    category: 'Mindfulness',
    Icon: Sparkles,
    bgColor: 'bg-amber-50',
    activeBg: 'bg-amber-500',
    textColor: 'text-amber-600',
    ringColor: 'ring-amber-500',
    emoji: '🧘',
    description: 'Breathing, meditation & presence',
  },
  {
    id: 'book',
    label: 'Reading',
    category: 'Mindfulness',
    Icon: BookOpen,
    bgColor: 'bg-blue-50',
    activeBg: 'bg-blue-600',
    textColor: 'text-blue-600',
    ringColor: 'ring-blue-600',
    emoji: '📖',
    description: 'Reading books & continuous study',
  },
  {
    id: 'brain',
    label: 'Deep Focus',
    category: 'Mindfulness',
    Icon: Brain,
    bgColor: 'bg-fuchsia-50',
    activeBg: 'bg-fuchsia-600',
    textColor: 'text-fuchsia-600',
    ringColor: 'ring-fuchsia-600',
    emoji: '🧠',
    description: 'Mental stamina & deep work blocks',
  },
  {
    id: 'smile',
    label: 'Gratitude',
    category: 'Mindfulness',
    Icon: Smile,
    bgColor: 'bg-yellow-50',
    activeBg: 'bg-yellow-500',
    textColor: 'text-yellow-700',
    ringColor: 'ring-yellow-500',
    emoji: '✨',
    description: 'Gratitude journal & positive outlook',
  },
  {
    id: 'leaf',
    label: 'Nature / Green',
    category: 'Mindfulness',
    Icon: Leaf,
    bgColor: 'bg-emerald-50',
    activeBg: 'bg-emerald-600',
    textColor: 'text-emerald-600',
    ringColor: 'ring-emerald-600',
    emoji: '🌱',
    description: 'Time in nature & sustainability',
  },

  // Lifestyle & Productivity
  {
    id: 'sun',
    label: 'Morning Sun',
    category: 'Lifestyle',
    Icon: Sun,
    bgColor: 'bg-amber-50',
    activeBg: 'bg-amber-500',
    textColor: 'text-amber-600',
    ringColor: 'ring-amber-500',
    emoji: '☀️',
    description: 'Early morning sunlight & waking up',
  },
  {
    id: 'moon',
    label: 'Sleep & Night',
    category: 'Lifestyle',
    Icon: Moon,
    bgColor: 'bg-indigo-50',
    activeBg: 'bg-indigo-600',
    textColor: 'text-indigo-600',
    ringColor: 'ring-indigo-600',
    emoji: '🌙',
    description: 'Evening wind-down & 8h sleep',
  },
  {
    id: 'bed',
    label: 'Rest & Recovery',
    category: 'Lifestyle',
    Icon: Bed,
    bgColor: 'bg-violet-50',
    activeBg: 'bg-violet-600',
    textColor: 'text-violet-600',
    ringColor: 'ring-violet-600',
    emoji: '🛏️',
    description: 'Quality sleep & physical recovery',
  },
  {
    id: 'coffee',
    label: 'Mindful Coffee',
    category: 'Lifestyle',
    Icon: Coffee,
    bgColor: 'bg-stone-50',
    activeBg: 'bg-amber-700',
    textColor: 'text-amber-800',
    ringColor: 'ring-amber-700',
    emoji: '☕',
    description: 'Coffee ritual & morning kickoff',
  },
  {
    id: 'clock',
    label: 'Time Blocking',
    category: 'Lifestyle',
    Icon: Clock,
    bgColor: 'bg-slate-50',
    activeBg: 'bg-slate-700',
    textColor: 'text-slate-700',
    ringColor: 'ring-slate-700',
    emoji: '⏰',
    description: 'Punctuality & scheduled blocks',
  },
  {
    id: 'code',
    label: 'Coding & Dev',
    category: 'Lifestyle',
    Icon: Code,
    bgColor: 'bg-indigo-50',
    activeBg: 'bg-blue-600',
    textColor: 'text-blue-700',
    ringColor: 'ring-blue-600',
    emoji: '💻',
    description: 'Programming & software practice',
  },
  {
    id: 'music',
    label: 'Music Practice',
    category: 'Lifestyle',
    Icon: Music,
    bgColor: 'bg-purple-50',
    activeBg: 'bg-purple-600',
    textColor: 'text-purple-600',
    ringColor: 'ring-purple-600',
    emoji: '🎵',
    description: 'Instrument rehearsal & ear training',
  },
  {
    id: 'palette',
    label: 'Creative Art',
    category: 'Lifestyle',
    Icon: Palette,
    bgColor: 'bg-pink-50',
    activeBg: 'bg-pink-500',
    textColor: 'text-pink-600',
    ringColor: 'ring-pink-500',
    emoji: '🎨',
    description: 'Sketching, painting & creativity',
  },
  {
    id: 'wallet',
    label: 'Budgeting',
    category: 'Lifestyle',
    Icon: Wallet,
    bgColor: 'bg-emerald-50',
    activeBg: 'bg-emerald-600',
    textColor: 'text-emerald-700',
    ringColor: 'ring-emerald-600',
    emoji: '💰',
    description: 'Track expenses & save daily',
  },
];

export function getHabitIconDefinition(iconId?: string): HabitIconDefinition {
  const found = HABIT_ICONS_LIST.find((item) => item.id === iconId);
  if (found) return found;

  // Fallback icon
  return {
    id: 'water',
    label: 'Habit',
    category: 'Lifestyle',
    Icon: Sparkles,
    bgColor: 'bg-emerald-50',
    activeBg: 'bg-emerald-600',
    textColor: 'text-emerald-600',
    ringColor: 'ring-emerald-600',
    emoji: '⭐',
    description: 'Personal habit target',
  };
}
